config/routes.rb
KaisenDaichi::Application.routes.draw do
  resources :categories

  get "store/index"
  get "store/suppliers"
  get "store" => "store#index" , :as => :store
  post "store/checkout", :as => :checkout
  post "store/save_order", :as => :save_order
  post "store/add_to_cart/:id" => "store#add_to_cart"
  post "store/empty_cart" => "store#empty_cart"
  post "store/remove_item_from_cart" => "store#remove_item_from_cart"
  resources :shops

  resources :products

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KaisenDaichi</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/store.html.haml
!!! 5
%html
  %head
    %meta{ "http-equiv" => "Content-Type", :content => "text/html:charset=utf-8" }
    %title 買鮮カタログ

    != stylesheet_link_tag 'reset', 'text', '960', 'store'
    != javascript_include_tag :defaults
    != csrf_meta_tag
  %body#store.container_12
    %div#header.grid_12
      %h1
        買鮮カタログ

    %div.clear
    %div#columns
      %div#side.grid_3
        %div#cart
          = render :partial => 'cart', :object => @cart
        %ul#nav
          %li
            = link_to "トップ", store_path

          %li
            %a{:href => "#"}ニュース

          %li
            %a{:href => "#"}お問合せ

          %li
            %a{:href => "#"}ご利用ガイド

      %div#main.grid_6.suffix_3
        - if flash[:notice]
          %div#notice= flash[:notice]
        != yield
      %div.clear
    %div#footer.grid_12
      %p Copylight (C) 2010 Enishi Tech Inc. All Rights Reserved.
    %div.crear